name: marble

x-backend-image-version: &backend-image-version
    image: europe-west1-docker.pkg.dev/marble-infra/marble/marble-backend:v0.38.5
x-frontend-image-version: &frontend-image-version
    image: europe-west1-docker.pkg.dev/marble-infra/marble/marble-frontend:v0.38.1

x-shared-environment: &shared-env
    ENV: ${ENV}
    MARBLE_APP_URL: ${MARBLE_APP_URL}
  #  SENTRY_DSN: ${SENTRY_DSN}
x-backend-environment: &backend-env
    #  LICENSE_KEY: ${LICENSE_KEY}

    PORT: ${API_PORT:-8080}

    PG_HOSTNAME: ${PG_HOSTNAME}
    PG_PORT: ${PG_PORT}
    PG_USER: ${PG_USER}
    PG_PASSWORD: ${PG_PASSWORD}
    PG_SSL_MODE: ${PG_SSL_MODE}
    PG_CONNECTION_STRING: ${PG_CONNECTION_STRING}

    #  AUTHENTICATION_JWT_SIGNING_KEY: ${AUTHENTICATION_JWT_SIGNING_KEY}

    INGESTION_BUCKET_URL: ${INGESTION_BUCKET_URL}
    CASE_MANAGER_BUCKET_URL: ${CASE_MANAGER_BUCKET_URL}

    GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}
    GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}

    #  REQUEST_LOGGING_LEVEL: ${REQUEST_LOGGING_LEVEL}
    #  LOGGING_FORMAT: ${LOGGING_FORMAT}

    CREATE_ORG_NAME: ${CREATE_ORG_NAME}
    CREATE_ORG_ADMIN_EMAIL: ${CREATE_ORG_ADMIN_EMAIL}

    #  METABASE_SITE_URL: ${METABASE_SITE_URL}
    #  METABASE_JWT_SIGNING_KEY: ${METABASE_JWT_SIGNING_KEY}
    #  METABASE_GLOBAL_DASHBOARD_ID: ${METABASE_GLOBAL_DASHBOARD_ID}

    CONVOY_API_URL: ${CONVOY_API_URL}
    CONVOY_API_KEY: ${CONVOY_API_KEY}
    CONVOY_PROJECT_ID: ${CONVOY_PROJECT_ID}

    #  OPENSANCTIONS_API_HOST: ${OPENSANCTIONS_API_HOST}
    #  OPENSANCTIONS_AUTH_METHOD: ${OPENSANCTIONS_AUTH_METHOD}
    OPENSANCTIONS_API_KEY: ${OPENSANCTIONS_API_KEY}

    SEGMENT_WRITE_KEY: UgkImFmHmBZAWh5fxIKBY3QtvlcBrhqQ
x-frontend-environment: &frontend-env
    NODE_ENV: production
    PORT: ${APP_PORT:-8080}

    SESSION_SECRET: ${SESSION_SECRET}
    SESSION_MAX_AGE: ${SESSION_MAX_AGE}

    MARBLE_API_URL_CLIENT: ${MARBLE_API_URL_CLIENT}
    MARBLE_API_URL_SERVER: ${MARBLE_API_URL_SERVER}

    FIREBASE_PROJECT_ID: ${GOOGLE_CLOUD_PROJECT}
    FIREBASE_API_KEY: ${FIREBASE_API_KEY}
    FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
    FIREBASE_APP_ID: ${FIREBASE_APP_ID}

    SEGMENT_WRITE_KEY: AnqbZOIJ8TvCbQUhXLqin1tXXnxHX0CE

services:
    # NB: the docker compose file includes a postgres image for the sake of completeness, but we strongly
    # suggest using a production-grade database to run Marble in a production environment
  db:
      container_name: marble-postgres
      image: postgres:15
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: ${PG_PASSWORD:-changeme}
        POSTGRES_DB: marble
        PGDATA: /data/postgres
        PGPORT: ${PG_PORT:-5432}
      ports:
        - ${PG_PORT:-5432}:${PG_PORT:-5432}
      volumes:
        - marble_marble-db:/data/postgres
        - postgres-data:/var/lib/postgresql/data
      healthcheck:
        test: [ "CMD", "pg_isready", "-U", "postgres", "-h", "marble-postgres" ]
        interval: 10s
        retries: 5
        timeout: 5s

  api: &backend
      <<: *backend-image-version
      container_name: marble-api
      platform: linux/amd64
      restart: always
      depends_on:
        - db
        - yente
      entrypoint: [ "./app", "--server", "--migrations" ]
      healthcheck:
        test: wget --no-verbose --tries=1 --spider http://localhost:${API_PORT:-8080}/liveness || exit 1
        interval: 10s
        timeout: 60s
        retries: 1
        start_period: 30s
      ports:
        - ${HOST_API_PORT:-8080}:${API_PORT:-8080}
      volumes:
        - ./local_shared:/shared
        - /mnt/c/Users/DELL/Downloads/marble-8ee29-ad3ba461c0d3.json:/service-account.json:ro
      environment:
        <<: [ *shared-env, *backend-env ]
        CONVOY_API_URL: "http://convoy-m:8080"
        CONVOY_API_KEY: ${CONVOY_API_KEY}
      networks:
        - marble-network

  cron:
      <<: *backend
      container_name: marble-api-cron
      depends_on:
        - api
      entrypoint: [ "./app", "--worker" ]
      healthcheck:
        disable: true
        test: [ "CMD", "curl", "-f", "http://localhost" ]
        interval: 1m30s
        timeout: 10s
        retries: 3
        start_period: 40s
      ports: [ ]
      volumes:
        - /mnt/c/Users/DELL/Downloads/marble-8ee29-ad3ba461c0d3.json:/service-account.json:ro
      networks:
        - marble-network


  app:
      <<: *frontend-image-version
      container_name: marble-app
      platform: linux/amd64
      restart: always
      depends_on:
        - api
      healthcheck:
        test: curl --fail http://localhost:${APP_PORT:-8080}/healthcheck || exit 1
        interval: 10s
        timeout: 60s
        retries: 1
        start_period: 30s
      ports:
        - ${HOST_APP_PORT:-3000}:${APP_PORT:-8080}
      environment:
        <<: [ *shared-env, *frontend-env ]
      networks:
        - marble-network

    # NB: the docker compose file includes an elasticsearch image for the sake of completeness, but we strongly
    # suggest using a production-grade instance to run Marble in a production environment

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
      container_name: marble-es
      environment:
        - discovery.type=single-node
        - bootstrap.memory_lock=true
        - ES_JAVA_OPTS=-Xms1g -Xmx1g
        - xpack.security.enabled=false
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - es_data:/usr/share/elasticsearch/data
      ports:
        - "9200:9200"
      healthcheck:
        test: [ "CMD-SHELL", "curl --fail http://localhost:9200/_cluster/health || exit 1" ]
        interval: 10s
        timeout: 10s
        retries: 3
      networks:
        - marble-network

  yente:
      image: ghcr.io/opensanctions/yente:4.2.1
      container_name: marble-yente
      environment:
        - YENTE_ELASTICSEARCH_URL=http://marble-es:9200
        - YENTE_PORT=8000
      depends_on:
        - elasticsearch
      ports:
        - "8000:8000"
      networks:
        - marble-network

  convoy-postgres:
    image: postgres:15
    container_name: convoy_postgres
    environment:
        POSTGRES_DB: convoy
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: IruoVict21
    ports:
      - "5435:5432"
    volumes:
        - convoy_postgres_data:/var/lib/postgresql/data
    networks:
        - marble-network

  convoy-nginx:
    image: nginx:alpine
    ports:
      - "5000:80"  # Now access via port 5000 on host
    volumes:

      - /mnt/c/Users/DELL/marble/nginx-config:/etc/nginx/conf.d:ro
      - ./convoy:/var/www/html  # Same volume as PHP container
    depends_on:
      - convoy-panel
    networks:
      - marble-network

  convoy-panel:
    build:
        context: ./convoy
        dockerfile: dockerfiles/workspace/Dockerfile
    command: ["php-fpm", "-F", "-R"]
    env_file:
        - ./.env
#    ports:
#      - "5000:9000"
    volumes:
        - ./convoy:/var/www/html
    depends_on:
        - convoy-postgres
    networks:
        - marble-network



#  convoy:
#    image: getconvoy/convoy:latest
#    container_name: convoy-m
#    ports:
#      - "8081:8080"
#    depends_on:
#    - db
#    - redis
#    environment:
#      DATABASE_URL: "postgres://postgres:${PG_PASSWORD}@marble-postgres:5432/convoy"
#     # 🔹 Ingestion Bucket Configuration
#      STORAGE_INGESTION_MODE: "s3"
#      STORAGE_INGESTION_S3_ACCESS_KEY: ${SUPABASE_ACCESS_KEY}
#      STORAGE_INGESTION_S3_SECRET_KEY: ${SUPABASE_SECRET_ACCESS_KEY}
#      STORAGE_INGESTION_S3_BUCKET: ingestion-bucket-url
#      STORAGE_INGESTION_S3_REGION: eu-central-1
#      STORAGE_INGESTION_S3_ENDPOINT: ${SUPABASE_ENDPOINT}
#
#    # 🔹 Case Manager Bucket Configuration
#      STORAGE_CASE_MANAGER_MODE: "s3"
#      STORAGE_CASE_MANAGER_S3_ACCESS_KEY: ${SUPABASE_ACCESS_KEY}
#      STORAGE_CASE_MANAGER_S3_SECRET_KEY: ${SUPABASE_SECRET_ACCESS_KEY}
#      STORAGE_CASE_MANAGER_S3_BUCKET: marble-bucket
#      STORAGE_CASE_MANAGER_S3_REGION: eu-central-1
#      STORAGE_CASE_MANAGER_S3_ENDPOINT: ${SUPABASE_ENDPOINT}
#
#    # Redis Connection
#      REDIS_URL: "redis://redis:6379"
##    "ports:
##      - "8080:8080""
#    volumes:
#      - convoy-data:/var/www/convoy
#    networks:
#      - marble-network
#
#
#
##  convoy:
##     image: getconvoy/convoy:latest
##     container_name: convoy
##     ports:
##       - "5000:5000"
##     environment:
##       INGRESS_BASE_URL: "http://localhost:5000"
##       DATABASE_URL: "postgres://username:password@host:5432/database"
##     restart: always
#
#
##  convoy-ui:
##      image: convoy-image
##      container_name: convoy-ui
###      restart: always
##      ports:
##        - "8080:80"
##      depends_on:
##        - convoy
#
#
##  convoy:
##    image: convoypanel/convoy
##    container_name: convoy
##    ports:
##      - "80:80"
##    environment:
##      - APP_URL=http://localhost
##      - DB_DATABASE=convoy
##      - DB_USERNAME=convoy_user
##      - DB_PASSWORD=${PG_PASSWORD}
##      - REDIS_PASSWORD=${REDIS_PASSWORD}
##    depends_on:
##      - convoy-redis
##      - convoy-pgbouncer
##    networks:
##      - marble-network
#
#
#  pgbouncer:
#      image: pgbouncer/pgbouncer:latest
#      container_name: convoy-pgbouncer
#      restart: always
#      environment:
#        DATABASE_URL: "postgres://postgres:${PG_PASSWORD:-changeme}@marble-postgres:5434/marble?sslmode=disable"
#        DATABASES_HOST: marble-postgres
#        PG_DATABASE: marble
#        PG_HOST: postgresql
#        PG_PORT: ${PG_PORT}
#        PG_USER: postgres
#        DATABASE_PASSWORD: ${PG_PASSWORD}
#        POOL_MODE: transaction
#        MAX_CLIENT_CONN: 100
#        DEFAULT_POOL_SIZE: 20
#      ports:
#        - "6432:6432"
#      depends_on:
#        - db
#      networks:
#        - marble-network
#
##  convoy-pgbouncer:
##    image: pgbouncer/pgbouncer
##    container_name: convoy-pgbouncer
##    environment:
##      - DATABASE_URL="postgres://postgres:${PG_PASSWORD:-changeme}@marble-postgres:5434/marble?sslmode=disable"
##      - DATABASE_HOST=marble-postgres
##      - DB_PORT=5433
##      - DB_USER=${DB_USERNAME}
##      - DB_PASSWORD=${PG_PASSWORD}
##      - DB_NAME=${DB_DATABASE}
##    ports:
##      - "6432:6432"
##    networks:
##      - marble-network
#
#  redis:
#    image: redis:latest
#    container_name: convoy-redis
#    restart: always
#    ports:
#      - "6370:6379"
#    healthcheck:
#      test: [ "CMD", "redis-cli", "ping" ]
#      interval: 10s
#      timeout: 5s
#      retries: 3
#    volumes:
#      - redis-data:/data
#
#    networks:
#      - marble-network

networks:
  marble-network:
    driver: bridge


volumes:
  convoy-data:
  marble-data:
  redis-data:
  postgres-data:
  convoy_postgres_data:
  es_data:
    driver: local

  marble_marble-db:
    driver: local